service: miranda-backend
package:
  patterns:
    - "!./**"
    - "package.json"
    - "node_modules/**"
    - "dist/**"
provider:
  name: aws
  region: eu-west-3
  environment:
    PORT: ${env:PORT}
    MYKEY: ${env:MYKEY}
    BASEKEY: ${env:BASEKEY}
  runtime: nodejs20.x
  
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::${env:AWS_S3_BUCKET}"
        - "arn:aws:s3:::${env:AWS_S3_BUCKET}/*"

    - Effect: "Allow"
      Action:
        - "iam:CreateRole"
        - "iam:PassRole"
        - "lambda:CreateFunction"
        - "lambda:UpdateFunctionCode"
        - "lambda:UpdateFunctionConfiguration"
        - "apigateway:CreateRestApi"
        - "apigateway:PutMethod"
        - "apigateway:PutIntegration"
        - "apigateway:DeployApi"
        - "cloudformation:CreateStack"
        - "cloudformation:UpdateStack"
        - "cloudformation:DescribeStacks"
        - "cloudformation:DeleteStack"
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "*"

functions:
  app:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
