name: S3 uploadBucket

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        users: actions/checkout@v2

      - name: Connecting AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-session-name: uploadsession
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: sync bucket
        run: aws s3 sync ./src/ s3://${{ secrets.AWS_BUCKET_NAME }} --delete